### ISSUE TITLE
Carthage Issues

### ISSUE THREAD

**Issue by michaelfransen** [ReactiveX/RxSwift#327]
I am trying to add RxSwift to my project using Carthage. I am using Xcode 7.2. Here are the errors I am getting

```
*** Building scheme "RxBlocking-OSX" in Rx.xcworkspace
*** Building scheme "RxBlocking-tvOS" in Rx.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/cdefs.h:707:2: error: Unsupported architecture
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean 'uint64_t'?
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator9.1.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
```

**Comment by michaelfransen** [comment]
I found that I can get it to work if I build for just the iOS platform. 

```
carthage update --platform iOS
```

**Comment by kzaher** [comment]
Hi @michaelfransen ,

This looks like some kind of bad sideffect of Xcode 7.2 and Carthage ¯\\\_(ツ)\_/¯ .

I've performed integration tests on Sunday evening using Xcode 7.1 and they've passed.

The same problem exists for watchOS and tvOS.

When carthage generates this command ...
```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/kzaher/Projects/RxIntegrations/CarthageTest/Carthage/Checkouts/RxSwift/Rx.xcworkspace -scheme RxBlocking-tvOS -configuration Release -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO build
```

... build fails, even though previous command ...

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace /Users/kzaher/Projects/RxIntegrations/CarthageTest/Carthage/Checkouts/RxSwift/Rx.xcworkspace -scheme RxBlocking-tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO build
```

... works correctly.

I can build tvos just fine using Xcode for both device and simulator.

It would be great if somebody that is familiar with Carthage could take a look at this.

I currently don't know why this is happening.

**Comment by ikesyo** [comment]
Please use [Carthage 0.11](https://github.com/Carthage/Carthage/releases/tag/0.11) to work with Xcode 7.2.

**Comment by kzaher** [comment]
Thnx @ikesyo ,

I've tried using [Carthage 0.11 ](Carthage 0.11), and out integration tests pass now :)

**Comment by michaelfransen** [comment]
Thanks @ikesyo. I did this and it worked. I will close this issue.
