### ISSUE TITLE
share(replay: 0) crashes with "Fatal error: oldState.disposable != nil" on concurrent first subscriptions (regression in 6.10.0)

### ISSUE THREAD

**Issue by vadimvitvickiy** [ReactiveX/RxSwift#2718]
**Summary**

Since 6.10.0, subscribing to a cold `share(replay: 0, scope: .whileConnected)` (the default `.share()`) from two threads at the same time can crash with:

```
SingleAssignmentDisposable.swift:45: Fatal error: oldState.disposable != nil
```

6.9.1 is not affected. The bug is still present on current `main`.

**Root cause**

Regression introduced by 6e1ad1a8 ("Fix deadlock in share(replay:) with concurrent subscriptions"). In `ShareWhileConnected.subscribe`, `lock.unlock()` was moved above the observer insert:

```diff
         let connection = synchronized_subscribe(observer)
         let count = connection.observers.count
 
+        self.lock.unlock()
         let disposable = connection.synchronized_subscribe(observer)
-        lock.unlock()
```

`count` is snapshotted under the lock, but the insert now happens after unlock. Two threads racing the first subscription can both read `count == 0` before either inserts its observer, so both call `connection.connect()` on the same connection. `connect()` calls `subscription.setDisposable(...)` — a `SingleAssignmentDisposable` — twice, which hits `rxFatalError("oldState.disposable != nil")`.

The `ShareReplay1WhileConnected` variant was reworked correctly in the same commit (the insert stayed under the lock; only the replayed `.next` emission moved outside), so `share(replay: 1)` is not affected.

A secondary effect of the same change: an observer can be inserted into a connection that was disposed between the unlock and the insert (`ShareWhileConnectedConnection.synchronized_subscribe` has no `disposed` check), yielding a subscription that never receives events.

**Reproduction**

Crashes in well under a second on an M-series Mac with `swift run`:

```swift
import Foundation
import RxSwift

for _ in 0..<200_000 {
  let shared = Observable<Int>.never().share()
  let group = DispatchGroup()
  let lock = NSLock()
  var disposables: [Disposable] = []

  for _ in 0..<4 {
    group.enter()
    DispatchQueue.global().async {
      let d = shared.subscribe()
      lock.lock(); disposables.append(d); lock.unlock()
      group.leave()
    }
  }
  group.wait()
  disposables.forEach { $0.dispose() }
}
print("no crash")
```

Output on 6.10.0 / 6.10.1 / 6.10.2:

```
.../Sources/RxSwift/SingleAssignmentDisposable.swift:45: Fatal error: oldState.disposable != nil
```

The identical code on 6.9.1 completes all 200,000 iterations cleanly.

We also hit this in production (two services subscribing a shared stream from concurrent dispatch queues), with the crashing frames being `ShareWhileConnectedConnection.connect()` → `rxFatalError`.

**Suggested fix**

Restore the pre-6.10.0 shape — insert the observer before releasing the lock:

```swift
lock.lock()
let connection = synchronized_subscribe(observer)
let count = connection.observers.count
let disposable = connection.synchronized_subscribe(observer)
lock.unlock()

if count == 0 {
    connection.connect()
}
```

This cannot reintroduce the deadlock that 6e1ad1a8 fixed: the deadlock came from emitting the replayed element to the observer (user code) while holding the lock, which only the `replay: 1` variant does — `synchronized_subscribe` in the `replay: 0` variant only inserts into the observer bag under the same recursive lock and runs no user code.

**Workarounds** until a fix ships: pin 6.9.1, or use `share(replay: 1, scope: .whileConnected)` (unaffected).

**Environment**: RxSwift 6.10.0–6.10.2 and current `main`; reproduced on macOS (swift run, Xcode 26 toolchain) and in production on iOS.
