### ISSUE TITLE
Main actor-isolated class 'RxNavigationControllerDelegateProxy' has different actor isolation

### ISSUE THREAD

**Issue by nalexn** [ReactiveX/RxSwift#2347]
**Short description of the issue**:

I'm on v6.2.0 of RxSwift/RxCocoa, the code base compiles ok in Xcode 12.5.1

However, in Xcode 13.0 beta 5 there is the following compilation error in RxCocoa:

`Main actor-isolated class 'RxNavigationControllerDelegateProxy' has different actor isolation from nonisolated superclass 'DelegateProxy'`

**Expected outcome**:

No compilation error

**What actually happens**:

A compilation error

**Self contained code example that reproduces the issue**:

Not applicable

**RxSwift/RxCocoa/RxBlocking/RxTest version/commit**

  _v6.2.0_

**Platform/Environment**

  - [x] iOS
  - [ ] macOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] playgrounds

**How easy is to reproduce? (chances of successful reproduce after running the self contained code)**

  - [x] easy, 100% repro
  - [ ] sometimes, 10%-100%
  - [ ] hard, 2% - 10%
  - [ ] extremely hard, %0 - 2%

**Xcode version**:

```
  13.0 beta 5
```

**I have multiple versions of Xcode installed**:
  (so we can know if this is a potential cause of your issue)
  - [x] yes (which ones) 13.0 beta 5 and 12.5.1
  - [ ] no

**Level of RxSwift knowledge**:
  (this is so we can understand your level of knowledge
    and formulate the response in an appropriate manner)
  - [ ] just starting
  - [ ] I have a small code base
  - [x] I have a significant code base

**Comment by markst** [comment]
Also applies to:
```swift
Main actor-isolated class 'RxScrollViewDelegateProxy' has different actor isolation from nonisolated superclass 'DelegateProxy'
```
